add support for feature flags
frain-dev/convoy pull request #1054
Opened 2022-10-06 12:30 UTC by Dotunj

2022-10-13 13:00 UTC, jirevwe approved these changes

2022-10-14 16:51 UTC, Subomi requested changes
Nice! Please see below:

2022-10-14 16:51 UTC, Subomi commented on internal/pkg/fflag/flipt/client.go
> +package flipt
@Dotunj This library isn't doing too much; we shouldn't be logging here. The client code should handle logging while this library returns errors.

2022-10-14 16:51 UTC, Subomi commented on cmd/main.go
> +	fflag    fflag.FeatureFlag
@Dotunj We don't need this DI from the `cmd` package. From my understanding, this is only an HTTP Client. We should instantiate it where it's needed and call the API.

2022-10-14 16:51 UTC, Subomi commented on internal/pkg/fflag/noop/client.go
> +package noopfflag
@Dotunj I don't think we need a noop for this. From my understanding, It's an HTTP wrapper.

2022-10-24 13:15 UTC, jirevwe approved these changes

2022-10-24 13:31 UTC, danvixent approved these changes

2022-10-24 13:38 UTC, merged