add advanced signature apis
frain-dev/convoy pull request #1067
Opened 2022-10-13 14:48 UTC by danvixent

2022-10-19 06:46 UTC, Subomi requested changes
@danvixent FYI

2022-10-19 12:22 UTC, danvixent commented on datastore/models.go
> +func GetDefaultSignatureConfig() *SignatureConfiguration {
There are parts that need to be regenerated each time, e.g the UID field

2022-10-19 12:23 UTC, danvixent commented on datastore/models.go
> +	// Hash     string `json:"hash,omitempty" valid:"required~please provide a valid hash,supported_hash~unsupported hash type"`
Got it.

2022-10-24 03:52 UTC, Subomi approved these changes

2022-10-24 03:52 UTC, merged