Queryparam support
frain-dev/convoy pull request #1404
Opened 2023-02-28 02:49 UTC by surendratiwari3

2023-02-28 09:34 UTC, Subomi commented
Hey @surendratiwari3, The build is failing. Please can you check it out?

2023-02-28 11:25 UTC, surendratiwari3 commented
@Subomi can you check now?

2023-03-01 05:47 UTC, Subomi commented
@surendratiwari3 It seems the build still has problems.

2023-03-07 23:18 UTC, Subomi commented on services/event_service.go
> +		QueryParams: newMessage.QueryParams,
@surendratiwari3 I think It's better to limit this to the ingest path alone. I can't think of a good use-case for doing this via the API. Also, the contract will be confusing as to what is for our REST API and what should be proxied.

2023-03-07 23:19 UTC, Subomi commented on datastore/models.go
> +	QueryParams      url.Values            `json:"query_params" bson:"query_params"`
@surendratiwari3 We switched to `PostgreSQL` as our default store, you need to switch this up for it to work.

2023-03-07 23:20 UTC, Subomi requested changes
@surendratiwari3 The build is passing now, but I left some feedback. :)

2023-03-22 12:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/frain-dev/convoy?pullRequest=1404) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/frain-dev/convoy?pullRequest=1404) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/frain-dev/convoy?pullRequest=1404) it.</sub>

2023-06-07 09:26 UTC, subomi commented
Fixed in #1640

2023-06-07 09:26 UTC, closed without merging