Add custom response to source
frain-dev/convoy pull request #1605
Opened 2023-05-24 12:24 UTC by danvixent

2023-05-26 11:45 UTC, horlah commented
@Oluwadaminiola You can remove the supposed link to the custom response documentation here, we don't have any documentation for it.

cc @subomi

2023-05-28 08:48 UTC, subomi requested changes
@danvixent, @horlah FYI

1. Updating a source does not update the custom response body.
2. The update source form does not show the previously added response body but the previously added response content type.

2023-05-28 19:42 UTC, subomi approved these changes

2023-05-28 19:42 UTC, merged

2024-03-08 06:51 UTC, qbx2 commented
Hello. Is it possible to template response using request header values? I want to solve okta's one-time verification request (https://developer.okta.com/docs/concepts/event-hooks/#one-time-verification-request) using convoy, but the challenge requires to respond with header value (x-okta-verification-challenge) .