Support ingest query param
frain-dev/convoy pull request #1640
Opened 2023-06-06 11:22 UTC by danvixent

2023-06-06 15:39 UTC, jirevwe commented on api/ingest.go
> +		UpdatedAt:      time.Now(),
These are set by default

2023-06-06 15:52 UTC, jirevwe approved these changes

2023-06-06 16:42 UTC, Dotunj requested changes

2023-06-07 05:05 UTC, subomi approved these changes

2023-06-07 09:23 UTC, merged