feat: add UI support for webhook transform functions
frain-dev/convoy pull request #1761
Opened 2023-09-12 12:34 UTC by Oluwadaminiola

2023-09-12 18:22 UTC, horlah requested changes

2023-09-12 18:22 UTC, horlah commented on web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts
> +	setupTransformDialog() {
I don't understand this method, why aren't we calling the dialog close/open directly?

2023-09-12 18:28 UTC, Oluwadaminiola commented on web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts
> +	showTransformDialog = false;
The dialog affects the editor, when using the show/close method, the editor was not initialized and was showing up blank hence this route

2023-09-13 14:38 UTC, horlah commented on web/ui/dashboard/src/app/private/components/create-subscription/create-subscription.component.ts
> +	showTransformDialog = false;
Hmm, got that

2023-09-15 08:36 UTC, jirevwe approved these changes

2023-09-15 18:17 UTC, horlah requested changes

2023-09-15 18:17 UTC, horlah commented on web/ui/dashboard/src/app/private/components/create-transform-function/create-transform-function.component.ts
> +}`;
Please update this guy:
`/*  1. While you can write multiple functions, the main function
    called for your transformation is the transform function.
    
    2. The only argument acceptable in the transform function is
    the payload data.
    
    3. The transform method must return a value.
*/

const transform = (payload) => {
    // Transform function here
}
`

2023-09-15 18:18 UTC, horlah commented
@Oluwadaminiola, I'll update the design to accommodate console log messages.

2023-09-19 20:35 UTC, horlah commented on web/ui/dashboard/src/app/private/components/create-transform-function/create-transform-function.component.ts
> +}`;
@Oluwadaminiola Did you see this?

2023-09-19 20:38 UTC, horlah commented
@Oluwadaminiola The console should be open by default

2023-09-22 00:39 UTC, horlah approved these changes

2023-09-25 08:28 UTC, merged