Remove flipt in favour of lib implementation
frain-dev/convoy pull request #1797
Opened 2023-10-13 16:59 UTC by danvixent

2023-10-16 08:52 UTC, jirevwe commented on api/types/types.go
> +	FlagCtrl *fflag.Controller
Why not name it `Fflag`?

2023-10-16 08:53 UTC, jirevwe commented on config/config.go
> +	GA           bool `json:"ga" envconfig:"CONVOY_GA_FEATURES"`
Isn't GA implied when nothing is passed?

2023-10-16 19:53 UTC, subomi requested changes

2023-10-16 19:53 UTC, subomi commented on cmd/main.go
> +	var alpha bool
@danvixent You forgot to take these values out.

2023-10-16 19:53 UTC, subomi commented on datastore/models.go
> +type Flag struct {
@danvixent You forgot to remove these as well.

2023-10-16 19:53 UTC, subomi commented on datastore/models.go
> +type FlagType string
@danvixent Please move this to the `fflag` package.

2023-10-16 19:53 UTC, subomi commented on sql/1696938095.sql
> +CREATE TABLE IF NOT EXISTS convoy.feature_flags (
@danvixent You forgot to remove this as well.

2023-10-16 19:53 UTC, subomi commented on internal/pkg/fflag/fflag.go
> +func (c *FFlag) CanAccessFeature(key string, cfg *config.Configuration) bool {
@danvixent The logic here is not correct. We should compare if the retrieved `flagType` is less than or equal to the user's selection.

2023-10-19 08:45 UTC, jirevwe approved these changes

2023-10-19 11:41 UTC, subomi approved these changes

2023-10-19 11:55 UTC, merged