Add license feature gating
frain-dev/convoy pull request #2114
Opened 2024-08-05 14:48 UTC by danvixent

2024-08-17 10:31 UTC, jirevwe commented on api/api.go
> +		uiRouter.Get("/license_features", handler.GetLicenseFeatures)
this is a nitpick, but shouldn't this be
```suggestion
		uiRouter.Get("/licenses/{id}/features", handler.GetLicenseFeatures)
		
		or 
		
		uiRouter.Get("/licenses/features", handler.GetLicenseFeatures)
```

2024-08-17 10:32 UTC, jirevwe commented on api/handlers/license.go
> +	_ = render.Render(w, r, util.NewServerResponse("Login successful", h.A.Licenser.FeatureListJSON(), http.StatusOK))
+1

2024-08-17 10:33 UTC, jirevwe commented on api/handlers/shim.go
Will the removal break anything?

2024-08-17 10:42 UTC, jirevwe commented on internal/pkg/license/keygen/feature.go
> +func (p PlanType) IsValid() bool {
That is a weird name. Does this mean the community plan isn't valid?

2024-08-18 19:09 UTC, jirevwe commented on internal/pkg/license/keygen/keygen.go
> +		return nil, fmt.Errorf("license has no entitlements")
Should this be an error case?
Can't a license have zero entitlements?

2024-08-18 19:11 UTC, jirevwe commented on internal/pkg/license/noop/noop.go
Can we add the integration build tag to this so it only compiles when we atr testing

2024-08-18 19:19 UTC, jirevwe requested changes
I left a few comments; it looks good overall, though. Good job

2024-08-19 09:12 UTC, jirevwe commented on internal/pkg/license/keygen/keygen.go
> +	keygen.Account = "cb3ba418-a9a0-4aa1-8c20-a844a06eeac9"
Yeah, they are meant to be checked in

2024-08-19 09:16 UTC, jirevwe approved these changes

2024-08-19 10:57 UTC, danvixent commented on api/handlers/license.go
> +	_ = render.Render(w, r, util.NewServerResponse("Login successful", h.A.Licenser.FeatureListJSON(), http.StatusOK))
fixed

2024-08-19 11:00 UTC, danvixent commented on api/handlers/subscription.go
> +		_ = render.Render(w, r, util.NewErrorResponse("your instance does not have access to subscription filters, upgrade to access this feature", http.StatusBadRequest))
I'm unable to find the duplicate

2024-08-19 11:13 UTC, danvixent commented on net/dispatcher.go
> +func NewDispatcher(httpProxy string, licenser license.Licenser, enforceSecure bool) (*Dispatcher, error) {
I think it's better this way for mock testing.

2024-08-21 11:02 UTC, danvixent commented on net/dispatcher.go
> +func NewDispatcher(httpProxy string, licenser license.Licenser, enforceSecure bool) (*Dispatcher, error) {
@mekilis maybe but I reckon it will be more complex to do so

2024-08-22 07:44 UTC, jirevwe approved these changes

2024-08-30 14:11 UTC, merged