Minor fixes
frain-dev/convoy pull request #2152
Opened 2024-09-18 15:40 UTC by danvixent

- set cors allow origin to host
- fix expires_at format in email params
- fix reset.password.html

2024-09-19 22:58 UTC, subomi requested changes
@danvixent Please add a screenshot of the generated email.

2024-09-20 10:56 UTC, danvixent commented
<img width="571" alt="Screenshot 2024-09-20 at 11 56 01 AM" src="https://github.com/user-attachments/assets/e5e8a357-f67d-432f-a8b2-77f5583b48d6">
@subomi

2024-09-23 10:14 UTC, jirevwe approved these changes

2024-09-25 11:56 UTC, jirevwe approved these changes

2024-09-25 11:56 UTC, merged