implement native realm
frain-dev/convoy pull request #267
Opened 2021-12-15 00:48 UTC by danvixent

2021-12-27 12:58 UTC, Subomi requested changes
Early feedback: Please let's have consistent file names: `file-realm.go` should be `file_realm.go`

Please let's fix this for all affected files. @danvixent

2021-12-27 19:44 UTC, danvixent commented
@Subomi done

2021-12-31 12:35 UTC, Subomi requested changes
@danvixent FYI

2021-12-31 12:35 UTC, Subomi commented on auth/realm/native/native_realm.go
> +package native
@danvixent This needs to be tested.

2022-01-03 23:03 UTC, danvixent commented on api_key.go
> +type APIKeyRepo interface {
done

2022-01-04 08:28 UTC, danvixent commented on auth/realm/native/native_realm.go
> +package native
done

2022-01-13 20:33 UTC, closed without merging