Add Partial Index with Unique Constraint for Group Name
frain-dev/convoy pull request #366
Opened 2022-01-18 10:55 UTC by Dotunj

Resolves #363

2022-01-18 17:54 UTC, danvixent approved these changes

2022-01-18 17:55 UTC, danvixent commented
@Dotunj is it possible to have a test case for this?

2022-01-19 14:31 UTC, Dotunj commented
@danvixent Yeah, added a test case

2022-01-20 15:44 UTC, Subomi requested changes

2022-01-20 15:44 UTC, Subomi commented on datastore/mongo/group_test.go
> +func Test_CannotCreateGroupWithExistingName(t *testing.T) {
@Dotunj This should be a test table under `Test_CreateGroup`

2022-01-21 00:50 UTC, Subomi approved these changes

2022-01-21 00:50 UTC, merged