Pelumi/update/syncing UI library
frain-dev/convoy pull request #465
Opened 2022-02-19 13:41 UTC by Oluwadaminiola

synced core with current ui library

2022-02-19 14:18 UTC, horlah commented on web/ui/dashboard/src/styles.scss
> +@import 'https://frain-dev.github.io/ui-library/scss/main.scss';
Please remove

2022-02-19 14:18 UTC, horlah commented on web/ui/dashboard/src/styles.scss
> +// @import './scss/table';
Do you still need these?

2022-03-02 10:58 UTC, horlah requested changes

2022-03-02 10:58 UTC, horlah commented on web/ui/dashboard/src/styles.scss
> +@import 'https://frain-dev.github.io/ui-library/scss/main.scss';
Still pending @Oluwadaminiola

2022-03-02 10:58 UTC, horlah commented on web/ui/dashboard/src/styles.scss
> +// @import './scss/table';
Still pending @Oluwadaminiola

2022-03-02 10:59 UTC, horlah commented
Please update this branch with changes in `main` @Oluwadaminiola

2022-03-03 14:20 UTC, horlah commented
<img width="585" alt="Screenshot 2022-03-03 at 3 19 33 PM" src="https://user-images.githubusercontent.com/17768868/156582880-9e69a5c1-c23b-4a85-b129-a55843df1cef.png">

You missed this dropdown list style. @Oluwadaminiola

2022-03-03 14:23 UTC, Oluwadaminiola commented
> 

on it

2022-03-03 14:37 UTC, horlah commented
@Oluwadaminiola Please don't publish the update yet. Let's merge this update first, there is another PR I want to add to the next publication.
Also, this update is a blocker for me to complete some things here.

2022-03-03 15:05 UTC, horlah commented
<img width="477" alt="Screenshot 2022-03-03 at 4 03 32 PM" src="https://user-images.githubusercontent.com/17768868/156591436-f6c74a3f-1acb-4f51-8405-2b26540f90b5.png">

The space between the list item is too small, see the one below.

<img width="481" alt="Screenshot 2022-03-03 at 4 04 37 PM" src="https://user-images.githubusercontent.com/17768868/156591607-4b3ac114-7e5f-4e31-8f7e-882123db6bf8.png">

@Oluwadaminiola

2022-03-03 15:11 UTC, horlah commented
<img width="838" alt="Screenshot 2022-03-03 at 4 11 34 PM" src="https://user-images.githubusercontent.com/17768868/156592950-117783bf-8869-40b2-a719-2e66c50fc41b.png">

@Oluwadaminiola Did you review this section?

2022-03-03 15:36 UTC, horlah commented
<img width="918" alt="Screenshot 2022-03-03 at 4 35 10 PM" src="https://user-images.githubusercontent.com/17768868/156597527-46444415-eaf9-4acc-bdd5-9e545a16d984.png">

There is no space on the sides of the highlighted item on the table, check the design or previous implementation. @Oluwadaminiola

2022-03-04 21:02 UTC, merged