Updated angular app portal assets
frain-dev/convoy pull request #582
Opened 2022-04-05 10:40 UTC by Oluwadaminiola

In the pr, the images were replaced by svg images existing within the library

2022-04-05 10:47 UTC, horlah commented
@Oluwadaminiola Please see if you can put these SVG files in a separate file and link it to the HTML document.

Please don't forget to delete any image file or folder that might exist in the dashboard-component project.

2022-04-05 11:50 UTC, Oluwadaminiola commented
> @Oluwadaminiola Please see if you can put these SVG files in a separate file and link it to the HTML document.
> 
> Please don't forget to delete any image file or folder that might exist in the dashboard-component project.

okay

2022-04-05 18:33 UTC, horlah commented
@Oluwadaminiola What's the update on this?

2022-04-06 19:26 UTC, horlah approved these changes

2022-04-06 20:00 UTC, horlah requested changes

2022-04-06 20:00 UTC, horlah commented on web/components/app-portal-angular/projects/convoy-app/src/lib/convoy-app.component.ts
> +			this.getEventDeliveries()
This two shouldn't be called here

2022-04-06 20:08 UTC, Oluwadaminiola commented on web/components/app-portal-angular/projects/convoy-app/src/lib/convoy-app.component.ts
> +		this.getAppDetails()
okay

2022-04-06 20:26 UTC, horlah approved these changes
💪🏾

2022-04-06 20:33 UTC, merged