events integration tests
frain-dev/convoy pull request #643
Opened 2022-05-05 11:04 UTC by danvixent

2022-05-09 13:18 UTC, Subomi requested changes
@danvixent FYI

2022-05-09 13:18 UTC, Subomi commented on server/event_integration_test.go
> +	expectedStatusCode := http.StatusBadRequest
This is a bug, I created an issue for it here #650

2022-05-09 13:18 UTC, Subomi commented on server/event_integration_test.go
> +	require.Equal(s.T(), *event, respEvent)
Compare IDs.

2022-05-09 13:18 UTC, Subomi commented on server/event_integration_test.go
> +	require.Equal(s.T(), *eventDelivery, respEventDelivery)
Compare IDs. Forget clearing status.

2022-05-09 14:16 UTC, danvixent commented on server/event_integration_test.go
> +func newRequestAndResponder(method string, url string, body io.Reader) (*http.Request, *httptest.ResponseRecorder) {
1. The CI linter keeps flagging them as unused code, not sure why, so i moved it here temporarily.
2. okay
3. I'm aware, but in my opinion, this block of code is not complex enough but it is repeated several times throughout the tests that it warrants a small helper.

2022-05-09 14:16 UTC, danvixent commented on server/event_integration_test.go
> +func serialize(t *testing.T, obj interface{}) io.Reader {
> 1. The CI linter keeps flagging them as unused code, not sure why, so i moved it here temporarily.
Noted the rest.

2022-05-10 09:07 UTC, jirevwe approved these changes

2022-05-10 14:20 UTC, merged