add support for sources resource
frain-dev/convoy pull request #678
Opened 2022-05-20 15:00 UTC by Dotunj

2022-05-20 18:14 UTC, Subomi requested changes
@Dotunj FYI

2022-05-20 18:14 UTC, Subomi commented on server/route.go
> +				sourceRouter.Use(requireGroup(app.groupRepo, app.cache))
@Dotunj This needs to be under the `/ui` router too.

2022-05-23 07:45 UTC, jirevwe approved these changes

2022-05-23 10:42 UTC, Subomi approved these changes

2022-05-23 10:51 UTC, merged