projects integration v2
frain-dev/convoy pull request #696
Opened 2022-06-01 17:14 UTC by Oluwadaminiola

2022-06-02 13:43 UTC, horlah commented
<img width="965" alt="Screenshot 2022-06-02 at 2 41 25 PM" src="https://user-images.githubusercontent.com/17768868/171642718-234f6d44-91da-4d4e-85b1-baca257e2121.png">

@Oluwadaminiola Please sync with @Subomi; let's add a tooltip that explains the fields to the inputs in this screenshot for creating a project.

2022-06-02 15:42 UTC, horlah requested changes

2022-06-02 15:46 UTC, Oluwadaminiola commented on web/ui/dashboard/src/app/private/pages/create-project/create-project.component.html
> +		<app-create-app *ngIf="projectStage === 'createApplication'" (discardCreateApp)="projectStage = 'createSubscription'"></app-create-app>
okay, noted

2022-06-03 13:54 UTC, horlah approved these changes

2022-06-03 13:57 UTC, merged