add document_status filter to all find queries
frain-dev/convoy pull request #725
Opened 2022-06-08 21:06 UTC by danvixent

2022-06-09 17:16 UTC, Subomi approved these changes

2022-06-10 15:35 UTC, jirevwe requested changes

2022-06-10 15:35 UTC, jirevwe commented on datastore/mongo/mongo_test.go
> +	return "mongodb://localhost:27017/convoyxx"
This should not be hardcoded

2022-06-16 13:50 UTC, jirevwe approved these changes

2022-06-17 11:34 UTC, merged