bugfixes for v6
frain-dev/convoy pull request #786
Opened 2022-06-22 08:00 UTC by Oluwadaminiola

2022-06-22 08:11 UTC, jirevwe requested changes

2022-06-22 09:55 UTC, Oluwadaminiola commented on web/ui/dashboard/src/app/public/forgot-password/forgot-password.component.ts
> +			if (response.status === true) {
it can, it can also be a number hence the conditional

2022-06-23 11:17 UTC, horlah commented on web/ui/dashboard/src/app/private/components/add-analytics/add-analytics.component.html
> +		<p class="font__14px color__grey margin-bottom__20px width__80">Enabling Analytics would allow anonymous metrics to be taken to see how Convoy is being used.</p>
Please update the text here to: Enabling Analytics will provide anonymous metrics to help us understand how you use Convoy, so we can make it even better for you.

2022-06-23 16:32 UTC, horlah requested changes

2022-06-23 16:32 UTC, horlah commented on web/ui/dashboard/src/app/private/pages/project/apps/apps.component.html
> +											<li (click)="deleteApplication($event, app)" class="danger">Delete</li>
I have an issue with having a click event on a `li` element

2022-06-23 16:32 UTC, horlah commented on web/ui/dashboard/src/app/private/pages/project/apps/apps.component.ts
> +	deleteApplication(event: MouseEvent, app: APP) {
I think `promptDeleteModal` will be a better name here. It better describes the action to be taken here.

2022-06-23 16:40 UTC, horlah commented
<img width="675" alt="Screenshot 2022-06-23 at 5 32 43 PM" src="https://user-images.githubusercontent.com/17768868/175349539-e09805d1-9470-41ea-bf60-f5381874f162.png">

Please a couple of things here:
- Update the element containing ' Would you like to enable analytics? ' to `h5` and set its `font-weight` to `500`.
- Add some space above the paragraph, `12px` should be good.
- Lastly, please reduce the width of the modal. You can use the same width I suggested for the delete modal.

@Oluwadaminiola

2022-06-24 09:59 UTC, horlah requested changes

2022-06-24 09:59 UTC, horlah commented on web/ui/dashboard/src/app/private/private.component.html
> +							<a (click)="selectOrganisation(organisation)" class="flex flex__justify-between padding-x__16px padding-y__8px">
Why not use a button, instead of an anchor?

2022-06-24 09:59 UTC, horlah commented on web/ui/dashboard/src/app/private/pages/project/events/events.component.html
> +					<a (click)="dashboardFrequency = filterOption; fetchDashboardData(); showFilterDropdown = false; showOverlay = false">{{ filterOption }}</a>
Why not make this a button

2022-06-24 09:59 UTC, horlah commented on web/ui/dashboard/src/app/private/pages/project/apps/apps.component.html
> +												<a (click)="promptDeleteModal($event, app)" class="color__danger">Delete</a>
Why not make this a button

2022-06-24 10:37 UTC, horlah approved these changes

2022-06-24 11:44 UTC, jirevwe approved these changes

2022-06-24 11:44 UTC, merged