Empty state story
frain-dev/convoy pull request #937
Opened 2022-08-11 14:03 UTC by Oluwadaminiola

2022-08-16 14:03 UTC, horlah requested changes

2022-08-16 14:03 UTC, horlah commented on web/ui/dashboard/src/stories/empty-state/Empty-state.stories.ts
> +        class: {
This is not needed here

2022-08-16 14:03 UTC, horlah commented on web/ui/dashboard/src/stories/empty-state/Empty-state.stories.ts
> +        class: {
We're meant to show the components in their natural state

2022-08-16 14:04 UTC, horlah commented
<img width="615" alt="Screenshot 2022-08-16 at 3 03 50 PM" src="https://user-images.githubusercontent.com/17768868/184899432-c2e136c5-f76c-410e-a1ad-a2e44e8049d4.png">

I can't edit controls here.

2022-08-16 17:40 UTC, horlah commented
I might have misdirected about removing the class property in the stories you created. Leaving the class there will allow us to test some styles on the component while testing or before applying it to the main component; since we're using Tailwind everywhere.

What do you think @Oluwadaminiola

2022-08-17 05:12 UTC, Oluwadaminiola commented
> I might have misdirected about removing the class property in the stories you created. Leaving the class there will allow us to test some styles on the component while testing or before applying it to the main component; since we're using Tailwind everywhere.
> 
> What do you think @Oluwadaminiola

yeah, I kind of agree with this, although due to the fact that most component stories are just standalone, the use cases for using the class property would be a bit limited, hence why I didn't necessarily add them to every story

2022-08-17 13:32 UTC, merged